### PR TITLE
contrib/go-redis/redis.v8: add WithSkipRawCommand option and fix resource

### LINKED ISSUE #1022: contrib/go-redis/redis.v8: Allow Option To Remove Raw Tag
I believe there's a case where if the command is sufficiently large, this will cause serious memory issues on the client. Not only that, I believe this should be optional because in certain cases, this could be a security issue. Therefore, we should allow an option to remove the raw tag.

To refresh, see snippet from the contrib hook. See the `raw_command` part.
```
	raw := cmd.String()
	length := strings.Count(raw, " ")
	p := ddh.params
	opts := make([]ddtrace.StartSpanOption, 0, 5+len(ddh.additionalTags)+1) // 5 options below + for additionalTags + for analyticsRate
	opts = append(opts,
		tracer.SpanType(ext.SpanTypeRedis),
		tracer.ServiceName(p.config.serviceName),
		tracer.ResourceName(raw[:strings.IndexByte(raw, ' ')]),
		tracer.Tag("redis.raw_command", raw),
		tracer.Tag("redis.args_length", strconv.Itoa(length)),
	)
```

The implementation of `cmd.String()` (I believe) boils down to this. You can see that it contains args.
```
func cmdString(cmd Cmder, val interface{}) string {
	b := make([]byte, 0, 64)

	for i, arg := range cmd.Args() {
		if i > 0 {
			b = append(b, ' ')
		}
		b = internal.AppendArg(b, arg)
	}

	if err := cmd.Err(); err != nil {
		b = append(b, ": "...)
		b = append(b, err.Error()...)
	} else if val != nil {
		b = append(b, ": "...)
		b = internal.AppendArg(b, val)
	}

	return internal.String(b)
}
```

Interestingly, there's been a similar feature request and subsequent revert for memcache:
- See request in #640. I think a bit indicative that the issue reporter blacked out the raw command in the screenshot + implemented it in a way that replicates that behavior in #642.
- It was reverted in #664 for reasons that I believe would apply here as well.

We've been able to isolate the problem to tracing by removing Redis tracing from the codepath that OOM'ed our servers without issue. But we haven't been able to dive into it in a more granular fashion than that. Happy to be told I'm wrong.

### PR DESCRIPTION
**Pull request by gbbr**
This change adds a new option called `WithSkippedRawCommand` which
determines the instrumentation code to skip adding the
`redis.raw_command` tag to spans. This is useful in cases when the
Datadog Agent Redis obfuscation is disabled (which it is, by default)
and commands may contain sensitive information.

Additionally, duplicate entries and an incosistency was found when
setting the resource name for Redis spans, which was fixed as part of
this PR.

Closes #1022

### CODE REVIEW

**Comment by dianashevchenko** [comment]
LGTM

**Review by shannontan-bolt — DISMISSED** [review]
Not sure my approval matters, but this will be a big help for sure!

**Comment by gbbr** [comment]
@shannontan-bolt it does matter. I want to make sure this is what you wanted and what we discussed.

**Comment by shannontan-bolt** [comment]
> @shannontan-bolt it does matter. I want to make sure this is what you wanted and what we discussed.

Ah - it is! I just mean that I don't think my approval is one that unblocks merge haha

**Pull request merged**
