### PR TITLE
internal/appsec/waf: strip libddwaf.a

### PR DESCRIPTION
**Pull request by Julio-Guerra**
Decrease libddwaf.a's size by stripping the unneeded symbols and debug information.
The resulting files are x10 smaller with 1.4 MB for macOS and 3.0 MB for linux.

Limits the problem reported at https://github.com/DataDog/dd-trace-go/issues/1055.

### CODE REVIEW

**Review by gbbr — DISMISSED** [review]

**Review by gbbr — APPROVED** [review]
Well done!

**Comment by felixge** [comment]
I'm a bit surprised the symbol tables are so big 👀. Additionally I'm worried that stripping them will reduce our ability to debug/profile the WAF. Do you see a better way to manage the WAF dependency for customers who don't use AppSec in the future that won't require us to ship with debug symbols?

**Comment by gbbr** [comment]
If it's not always needed (but I think it is?), maybe we can make it into a module. AFAIK [it gets pruned](https://golang.org/ref/mod#graph-pruning) when not used and the binary size is reduced. Actually, I think it was a module in the original PR. Have you explored this?

**Comment by felixge** [comment]
@Julio-Guerra thx, sounds good.

**Pull request merged**
