### PR TITLE
contrib: actually run integration tests

### PR DESCRIPTION
**Pull request by knusbaum**
Bad news.

Looks like we've not actually been running the integration tests for the contrib...

Worse, they seem to not be passing.

### CODE REVIEW

**Comment by knusbaum** [comment]
Mongo fix for #996

**Review by felixge — APPROVED** [review]
LGTM. When did we break this? Was it my gotestsum patch?

**Review by gbbr — APPROVED** [review]

**Comment by knusbaum** [comment]
@felixge Yeah, it looks like it got left out during #959

**Review by Julio-Guerra — COMMENTED** [review]
Thanks for the fix 👍

So the env var `INTEGRATION` should be `1` to have them running, right?

I also had a look at the latest output and I wonder why it says there are errors: `DONE 742 tests, 25 skipped, 9 errors in 80.347`, along with 25 contrib tests still skipped.

**Pull request merged**
