### PR TITLE
ddtrace/tracer: go tracer tests lint.

### PR DESCRIPTION
**Pull request by yuanyuanzhao3**
DNMC-21.

### What does this PR do?
Lint.

### Motivation

Cleaner code and less annoying IDE warnings.

### Reviewer's Checklist

- [ ] Changed code has unit tests for its functionality at or near 100% coverage.
- [ ] [System-Tests](https://github.com/DataDog/system-tests/) covering this feature have been added and enabled with the va.b.c-dev version tag.
- [ ] There is a benchmark for any new code, or changes to existing code.
- [ ] If this interacts with the agent in a new way, a system test has been added.
- [ ] Add an appropriate team label so this PR gets put in the right place for the release notes.
- [ ] Non-trivial go.mod changes, e.g. adding new modules, are reviewed by @DataDog/dd-trace-go-guild.

For Datadog employees:

- [ ] If this PR touches code that handles credentials of any kind, such as Datadog API keys, I've requested a review from `@DataDog/security-design-and-guidance`.
- [X] This PR doesn't touch any of that.

Unsure? Have a question? Request a review!

### CODE REVIEW

**Review by felixge — APPROVED** [review]
The change reveals some haphazard error checking in our test code. But I can see no change in behavior, so this all looks good to me.

Out of curiosity, what IDE/linter are you using?

**Comment by yuanyuanzhao3** [comment]
@felixge FYI I do not have permission to merge the PR. There is a prompt here that mentions a merge queue. However, I do not see an option to "merge when ready". So if you are OK with this PR, can you trigger the merge? Thanks.

**Review by darccio — APPROVED** [review]

**Comment by felixge** [comment]
> @felixge FYI I do not have permission to merge the PR. There is a prompt here that mentions a merge queue. However, I do not see an option to "merge when ready". So if you are OK with this PR, can you trigger the merge? Thanks.

IIRC I was trying to merge it, but I wasn't able to, because we require CODEOWNER reviews in this repo. Anyway, thanks @darccio for getting it sorted 🙇

**Pull request merged**
