### PR TITLE
Setup Code Scanning on dd-trace-go

### PR DESCRIPTION
**Pull request by ganeshkumarsv**
Static code analysis on dd-trace-go using Github's Code Scanning.

This PR has Github workflow configs to trigger the Code Scanning on every PR and on push to master branch. As of now only default security based CodeQL queries are configured. We can gradually add queries for Code Quality later. It is a part of Datadog compliance requirements to regularly perform code-scanning on all the customer installed code.

### CODE REVIEW

**Review by knusbaum — DISMISSED** [review]

**Comment by knusbaum** [comment]
Let's fix the CodeQL error along with this PR so the tests don't start failing immediately.

**Comment by ganeshkumarsv** [comment]
@knusbaum Once the PR gets merged, this error from (`Code Scanning results / CodeQL`) will not show up on other PRs (only newly caught errors will show up and fail the job). And we will be creating Jira cards on Vulnerability Management board for tracking, so you have enough time to work on the alerts.

**Comment by ganeshkumarsv** [comment]
@knusbaum I have added the fix in this PR itself. Please review the fix as well. Thanks!

**Comment by ganeshkumarsv** [comment]
@knusbaum gentle reminder on the PR review! 🙏 🙇

**Review by knusbaum — APPROVED** [review]
Awesome, LGTM.

**Pull request merged**
