### PR TITLE
profiler: add support for DD_PROFILE_TYPES environment variable

### PR DESCRIPTION
**Pull request by afarbos**
Following the proposal https://github.com/DataDog/dd-trace-go/issues/1011, adding support to provide profile types using environment variables in the default configurations.

### CODE REVIEW

**Comment by felixge** [comment]
@afarbos thanks for this. I'll provide my review shortly!

**Review by felixge — APPROVED** [review]
Sorry for the delay. I just reviewed this and pushed the changes I was going to suggest into the PR, hope that's okay for you. The summary is:

- Added documentation
- Aligned the env var name with our env var naming conventions (`DD_PROFILING_` prefix)
- Made it so that the experimental goroutinewait profile is not enabled when the `"all"` option is set.
- Fix some gopls warnings

Anyway, this is a nice PR, thank you so much and thanks again for the delay. PTAL and let me know if you see any issue with my changes.

**Comment by afarbos** [comment]
> Details
 
This lgtm!

**Comment by felixge** [comment]
@afarbos hey, sorry this hasn't been merged yet. We're trying to standardize env variables like this across all our profilers but the discussions are still ongoing. I'll try to get the conclusions soon and then update this if needed.

**Comment by felixge** [comment]
Hey @afarbos this is still in our backlog. Hope to get to it soon!

**Comment by afarbos** [comment]
> Hey @afarbos this is still in our backlog. Hope to get to it soon!

@felixge Should I close this PR? or do we still intend to merge this?

**Comment by afarbos** [comment]
friendly bump @felixge, let me know.

**Comment by nsrip-dd** [comment]
Hi @afarbos, sorry again that this took so long to resolve. Unfortunately I don't think we'll commit to this configuration approach right now since it's inconsistent with how our other profiling client libraries are configured. The Node profiler supports a similar variable to this (they call it `DD_PROFILING_PROFILERS`). However, the Java, .NET, and Python profilers all have some variant of `DD_PROFILING_<TYPE>_ENABLED`, one for each kind of profiler the libraries support. On top of that, if we were doing an env-var-per-profile-type approach we might also want variables for configuring the sampling frequency/other parameters for each profile type. We have some precedent for that approach in this library with our "experimental" profile types. If we went with any kind of environment variable-based profile configuration, I think we'd go with one-per-profile-type rather than the comma-separated string.

All of this said, your suggestion isn't totally off the table and we might revisit this. In the mean time, something like this can be written just based on our public API without needing to access any internal details. Here's a snippet you're free to use: https://go.dev/play/p/Je9fcqHmBVi

**Pull request closed without merging**
