### PR TITLE
go.mod: remove inet.af/netaddr dependency

### LINKED ISSUE #2552: [BUG] - Unable to import tracer package
I'm trying to import the package into my project - `go get gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer` but I get the error below
`inet.af/netaddr@v0.0.0-20230525184311-b8eac61e914a: verifying module: inet.af/netaddr@v0.0.0-20230525184311-b8eac61e914a: cannot authenticate record data in server response`

**Version of dd-trace-go**

**Describe what happened:**
`inet.af/netaddr@v0.0.0-20230525184311-b8eac61e914a: verifying module: inet.af/netaddr@v0.0.0-20230525184311-b8eac61e914a: cannot authenticate record data in server response` 

**Describe what you expected:**
Should be able to import succesfully

**Steps to reproduce the issue:**
`go get gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer`

**Additional environment details (Version of Go, Operating System, etc.):**
Go - 1.21, MacOS

### PR DESCRIPTION
**Pull request by darccio**
### What does this PR do?

Removes `inet.af/netaddr`, upgrading `github.com/DataDog/appsec-internal-go` 
 (that removes the usage of `inet.af/netaddr` in https://github.com/DataDog/appsec-internal-go/pull/21).

### Motivation

This is needed because of the domain takedown by the Afghan government on several domains. Fixes #2552.

### Reviewer's Checklist

- [ ] Changed code has unit tests for its functionality at or near 100% coverage.
- [ ] [System-Tests](https://github.com/DataDog/system-tests/) covering this feature have been added and enabled with the va.b.c-dev version tag.
- [ ] There is a benchmark for any new code, or changes to existing code.
- [ ] If this interacts with the agent in a new way, a system test has been added.
- [ ] Add an appropriate team label so this PR gets put in the right place for the release notes.
- [ ] Non-trivial go.mod changes, e.g. adding new modules, are reviewed by @DataDog/dd-trace-go-guild.

For Datadog employees:

- [ ] If this PR touches code that handles credentials of any kind, such as Datadog API keys, I've requested a review from `@DataDog/security-design-and-guidance`.
- [ ] This PR doesn't touch any of that.

Unsure? Have a question? Request a review!

### CODE REVIEW

**Review by eliottness — APPROVED** [review]

**Comment by mraerino** [comment]
any idea when this is going to be part of a release?

**Comment by darccio** [comment]
@mraerino We are working on an expedited release. Does the workaround work for you?

**Comment by mraerino** [comment]
yeah, i think we'll be able to work around, just wanted to make sure when i can expect to properly fix this without a workaround

**Comment by darccio** [comment]
@mraerino Released as [v1.60.3](https://github.com/DataDog/dd-trace-go/releases/tag/v1.60.3).

**Pull request merged**
