### PR TITLE
contrib/go-chi: set the actual path instead of unknown

### LINKED ISSUE #1198: contrib/contrib/go-chi: set the resource the actual path instead of "unknown" at 404 HTTP code
I started to use the chi trace middleware and I realized that when the chi gets an unknown path in the HTTP request the middleware set "unknown" in the Datadog resource because in this case the `RoutePattern()` gives back an empty string. My proposal is in this case the resource should be the actual path. 

the actual code snippet:
```
	// set the resource name as we get it only once the handler is executed
	resourceName := chi.RouteContext(r.Context()).RoutePattern()
	if resourceName == "" {
		resourceName = "unknown"
	}
```

the changes would be:
```
	// set the resource name as we get it only once the handler is executed
	resourceName := chi.RouteContext(r.Context()).RoutePattern()
	if resourceName == "" {
		resourceName = r.URL.Path
		if resourceName == "" {
			resourceName = "unknown"
		}
	}
```

Any idea or suggestion?

### PR DESCRIPTION
**Pull request by taowata**
### What does this PR do?
This PR resolves an issue with the chi trace middleware setting the resourceName to "unknown" for undefined paths or validation errors. 

The change ensures the resourceName reflects the actual path when RoutePattern() returns an empty string.
### Motivation
Fixes #1198

### Describe how to test/QA your changes
To test/QA these changes, unit tests have been added to cover the following cases:

- When an HTTP request encounters an undefined path (404 error).
- When a validation middleware encounters an error.

### Reviewer's Checklist

- [ ] Changed code has unit tests for its functionality.
- [ ] If this interacts with the agent in a new way, a system test has been added.

### CODE REVIEW

**Comment by taowata** [comment]
As I commented in https://github.com/DataDog/dd-trace-go/issues/1198#issuecomment-1542347183, a better solution to this problem might be to allow customization of the resouceName as suggested in #1950.

**Comment by pcriv** [comment]
@taowata I see you re-opened this, are you planning to continue working on it?

**Comment by taowata** [comment]
@pcriv Yes, that's correct. I accidentally closed the PR but I'm planning to continue working on it.
I am waiting for feedback from the maintainers.

**Comment by taowata** [comment]
> We prefer not to expose the path by default due to policy. I'm keeping the PR open if you want to discuss other options for default behavior for "unknown" but we are merging #1950 soon which as you mentioned provides a more generic solution for this.
> 
> _Originally posted by @zarirhamza in https://github.com/DataDog/dd-trace-go/issues/1198#issuecomment-1572217739_

I have closed this PR in accordance with the policy mentioned in this comment.

**Pull request closed without merging**
