### PR TITLE
tools/v2check: basic implementation

### PR DESCRIPTION
**Pull request by darccio**
### What does this PR do?

Introduces `v2check`, the migration tool to simplify the upgrade from `dd-trace-go` v1.x to v2.0.0.

Fix suggestions will be implemented in a follow-up PR.

### Motivation

Preparing to release `dd-trace-go` v2.

### Reviewer's Checklist

- [ ] Changed code has unit tests for its functionality at or near 100% coverage.
- [ ] [System-Tests](https://github.com/DataDog/system-tests/) covering this feature have been added and enabled with the va.b.c-dev version tag.
- [ ] There is a benchmark for any new code, or changes to existing code.
- [ ] If this interacts with the agent in a new way, a system test has been added.
- [ ] Add an appropriate team label so this PR gets put in the right place for the release notes.

For Datadog employees:

- [ ] If this PR touches code that handles credentials of any kind, such as Datadog API keys, I've requested a review from `@DataDog/security-design-and-guidance`.
- [ ] This PR doesn't touch any of that.

Unsure? Have a question? Request a review!

### CODE REVIEW

**Comment by felixge** [comment]
Does this only report problems, or does it also automatically fix them? If it's the former, what are the plans for the latter?

**Comment by darccio** [comment]
> Does this only report problems, or does it also automatically fix them? If it's the former, what are the plans for the latter?

On release it'll report problems and suggest fixes. It'll also be possible to run with a `-fix` flag to automatically fix everything.

Fixes will be implemented in a follow-up PR.

**Review by ahmed-mez — APPROVED** [review]
LGMT, I assume the documentation to install and run the tool will be added later?

**Comment by darccio** [comment]
> LGMT, I assume the documentation to install and run the tool will be added later?

Yes, it will be done at release.

**Pull request merged**
