### PR TITLE
ddtrace/tracer: fix os version for builds on niche GOOS (e.g. freebsd, ...)

### LINKED ISSUE #753: Build fails everywhere except Linux, Windows, macOS
```
$ git clone https://github.com/DataDog/dd-trace-go  
$ cd dd-trace-go
$ GOOS=freebsd GOOARCH=amd64 go build ./ddtrace/tracer
# [...]
# gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer
ddtrace/tracer/osinfo_default.go:19:9: undefined: unknownVersion
```

### PR DESCRIPTION
**Pull request by aeneasr**
Closes #753

### CODE REVIEW

**Comment by gbbr** [comment]
Can we add a regression test for this?

**Comment by aeneasr** [comment]
A linter would probably do better here.

**Review by gbbr — APPROVED** [review]

**Review by knusbaum — APPROVED** [review]

**Comment by aeneasr** [comment]
Would it be possible to release this?

**Comment by gbbr** [comment]
Sure! This is worthy of a patch release since it breaks the build on some OSs, here it is: https://github.com/DataDog/dd-trace-go/releases/tag/v1.27.1

**Comment by aeneasr** [comment]
Appreciate the quick turnaround, thanks!

**Pull request merged**
