### PR TITLE
profiler: fix the defaultAPIURL

### PR DESCRIPTION
**Pull request by knusbaum**

### CODE REVIEW

**Comment by roopakv** [comment]
could you please release a new version with this change? @gbbr @knusbaum?

i came to this repo to post this error, but seems like it is already fixed :)
```
"2020/04/28 10:11:48 Datadog Tracer v1.23.0 ERROR: Uploading profile failed: Post "https://beta-intake.profile.datadoghq.com/v1/input": dial tcp: lookup beta-intake.profile.datadoghq.com: no such host. Trying again in 2.234126ms..., 1 additional messages skipped (first occurrence: 28 Apr 20 10:11 PDT)"
```

**Comment by dbenamydd** [comment]
Sorry about that! We restored `beta-intake`. Want to try again?

**Comment by roopakv** [comment]
@dbenamydd yay! it works

**Comment by roopakv** [comment]
@dbenamydd could you please keep beta-intake on until 1.24 is released?

**Comment by dbenamydd** [comment]
Yep!

**Pull request merged**
