### PR TITLE
contrib/labstack/echo.v4: added support for Echo v4

### PR DESCRIPTION
**Pull request by kuchlein**
Copied the contents of contrib/labstack/echo to echo.v4 and appended /v4
to any imports that referenced echo.

Fixes: #543

### CODE REVIEW

**Comment by gbbr** [comment]
There might be a mistake somewhere, we're getting:
```
package github.com/labstack/echo/v4: cannot find package "github.com/labstack/echo/v4" in any of:
	/usr/local/go/src/github.com/labstack/echo/v4 (from $GOROOT)
	/go/src/github.com/labstack/echo/v4 (from $GOPATH)
```

**Comment by cgilmour** [comment]
That error seems to be because it's not set up as a module (with `go.mod` and `go.sum`), so it treats the import path in the usual `GOPATH` way.

Adding the module details (with `go mod init` and `go mod tidy` would clear it up, but has some other consequences that will affect maintaining it.

**Comment by kuchlein** [comment]
@cgilmour you beat me to it. I was going to see about adding modules but didn't quite get to it before you. As you pointed out this is likely to have some larger side effects to how this is maintained going forward. Also I wasn't sure if we could get away with adding modules within `contrib` somewhere or if it needs to be at the top level.

**Comment by cgilmour** [comment]
We did some experimenting in the past, and the conclusion was that modules aren't easy to support with the current repo layout and import path.

There's a few solutions we could go with, and they'll get judged on their impact on end users as well as maintainers/contributors.

**Comment by gbbr** [comment]
Oh my! Indeed this means we've hit our first problem caused by us not supporting modules. While support for multi-module repos is possible today (https://github.com/golang/go/issues/27056), I'm frankly still not fully comfortable that this is a good move and it seems like it might bring a lot of trouble and difficulties (https://github.com/golang/go/issues/26640, https://github.com/golang/go/issues/27542, https://github.com/golang/go/issues/28835).

If the pressure becomes high, and more problems like this come up, we'll be forced to switch to modules, but I'd like to prolong that decision as much as possible, hoping that the ecosystem will present solutions to the issues mentioned above.

I wondering if it would work to make a module only of this integration, and leave the rest as is, or if we'd have to go all in?

Relates to https://github.com/DataDog/dd-trace-go/issues/471

**Comment by jeanhalle** [comment]
Any update on this?

**Comment by gbbr** [comment]
No updates yet. Please follow the related issue. We will post updates there as soon as we start working on this...

**Comment by priyanshi-gupta** [comment]
#698 has been merged and targeted for 1.26.0 release

**Pull request closed without merging**
