### PR TITLE
ddtrace/tracer: tracer defaults from environment variables

### LINKED ISSUE #16: configuration environment variables
it might be nice to allow environment variables to configure the tracing client. i think we need the following and it should be consistent across all clients (with the implied defaults)

```
DATADOG_TRACE_TARGET=localhost:7777
DATADOG_TRACE_ENABLED=true
```

### PR DESCRIPTION
**Pull request by blaketastic2**
This feature adds in reading environment variables to set default values for the tracer.

Currently supporting environment variables:
- `DD_SERVICE_NAME`
- `DD_TRACE_GLOBAL_TAGS`

Fixes #16

### CODE REVIEW

**Comment by gbbr** [comment]
Hi Blake!

Thank you for your very first contribution. I would like you to take a moment and read [our contribution guidelines](https://github.com/DataDog/dd-trace-go/blob/v1/CONTRIBUTING.md), before committing to any work. More specifically the part:

> Pull requests for bug fixes are welcome, but before submitting new features or changes to current functionalities open an issue and discuss your ideas or propose the changes you wish to make. After a resolution is reached a PR can be submitted for review.

Thank you!

**Comment by blaketastic2** [comment]
@gbbr I started that direction, but found an issue that was similar to the one I was opening. Just updated the description to have the link to the issue.

**Comment by gbbr** [comment]
That ticket is closed and resolved. I'm afraid you'll have to open a new ticket and describe the problem you are trying to solve, along with the suggested solution. After we find common ground and a potential solution, we might move onto writing code.

Thanks for understanding.

**Comment by blaketastic2** [comment]
@gbbr Thank you for taking the time to get this done the correct way. I've closed my PR since it was not agreed on. Hopefully we can use #500 as a talking point.

**Pull request closed without merging**
