### PR TITLE
ci: disable gci

### PR DESCRIPTION
**Pull request by felixge**
### What does this PR do?

ci: disable gci

### Motivation

See PROF-8609 for more info.

### Reviewer's Checklist

- [ ] Changed code has unit tests for its functionality at or near 100% coverage.
- [ ] There is a benchmark for any new code, or changes to existing code.
- [ ] If this interacts with the agent in a new way, a system test has been added.

For Datadog employees:

- [ ] If this PR touches code that handles credentials of any kind, such as Datadog API keys, I've requested a review from `@DataDog/security-design-and-guidance`.
- [ ] This PR doesn't touch any of that.

Unsure? Have a question? Request a review!

### CODE REVIEW

**Review by ahmed-mez — APPROVED** [review]
Thanks!

**Review by RomainMuller — APPROVED** [review]

**Comment by Julio-Guerra** [comment]
I was suggesting on slack to either:
1. Relax the coding style defined in our wiki if we don't enforce it with CI
2. Or update de CI to auto-apply the import fixes rather than printing a warning

I'd favor 2 for the sake of aligning with the datadog-agent coding style.

**Comment by felixge** [comment]
> I was suggesting on slack to either:
> 
> 1. Relax the coding style defined in our wiki if we don't enforce it with CI
> 2. Or update de CI to auto-apply the import fixes rather than printing a warning
> 
> I'd favor 2 for the sake of aligning with the datadog-agent coding style.

I'm open to doing either of these things, but I'm merging this PR for now and then we can do whatever we decide next as a separate PR. Hope it's okay? (If not we can rollback)

**Pull request merged**
