### PR TITLE
tracer: merge support for OTel API

### PR DESCRIPTION
**Pull request by dianashevchenko**
### What does this PR do?

This PR adds support for an OpenTelemetry compatible API which wraps the Datadog API.

### Motivation

This can make it easier for dd-trace-go users who have already instrumented their code with OpenTelemetry and want to utilize the features of the dd-trace-go library with as few code changes as possible. Migrating from using the upstream OTel SDK (or another OTel API implementation) to using this Datadog OTel API should be as simple as subbing out their existing `TracerProvider` for ours.

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Changed code has unit tests for its functionality.
- [ ] If this interacts with the agent in a new way, a system test has been added.

### CODE REVIEW

**Comment by ahmed-mez** [comment]
We should revert https://github.com/DataDog/dd-trace-go/pull/1849 as part of this PR.

**Comment by dianashevchenko** [comment]
We have run locally the parametric tests with all the tests unskipped

**Comment by ahmed-mez** [comment]
But we still want to tests to run on main as well right?

**Comment by dianashevchenko** [comment]
Sure, but for that we have to remove the fix and unskip the tests in parametric, introducing a blocker again. So for now, we're running tests manually

**Comment by ahmed-mez** [comment]
Unskipping the tests won't break main since we're pinning an older version of system-tests that doesn't contain otel tests at all

**Comment by dianashevchenko** [comment]
> We have run locally the parametric tests with all the tests unskipped

This comment is not related to a previous comment of Ahmed.

**Comment by ahmed-mez** [comment]
Sorry for the confusion lol!

**Review by ajgajg1134 — APPROVED** [review]
Looks good to me!

**Pull request merged**
