### PR TITLE
.circleci: Add check for grouping imports

### PR DESCRIPTION
**Pull request by piochelepiotr**
Goimports supports the `-local` parameter to separate the local imports from the other ones. We can use it in the CI to ensure consistency in our imports.

### CODE REVIEW

**Comment by knusbaum** [comment]
@piochelepiotr This looks like a good addition to the CI.
What remains for it to come out of draft status?

**Comment by knusbaum** [comment]
@piochelepiotr I think we want this change.
Will you be able to finish this PR?

**Comment by piochelepiotr** [comment]
@knusbaum , I'm sorry I missed the notification. I just marked it as ready for review.

**Review by knusbaum — COMMENTED** [review]
This looks mostly good, but it looks to be like we're only doing the `ddtrace/tracer` package. Is there a reason we don't want to do the full module?

**Review by knusbaum — APPROVED** [review]
LGTM. Thanks.

**Pull request merged**
