### PR TITLE
tracer: profiler endpoints for spans without type

### PR DESCRIPTION
**Pull request by felixge**
See PROF-4730 (dd internal) for more info.

This should be the last missing thing before v1.35.0 can go out 🥳

### CODE REVIEW

**Review by nsrip-dd — COMMENTED** [review]
Looks good. Should the `WithProfilerEndpoints` doc be updated too?

**Comment by felixge** [comment]
> Looks good. Should the `WithProfilerEndpoints` doc be updated too?

Nice catch ➡️ 37092cb3057fba200120e3484eb720222ae20d54. PTAL again :)

**Review by nsrip-dd — APPROVED** [review]
LGTM 👍

**Comment by felixge** [comment]
Thanks for the reviews nick!

**Pull request merged**
