### PR TITLE
contrib/99designs/gqlgen: fix issue with example import in tests

### PR DESCRIPTION
**Pull request by david-alza**
Addresses: https://github.com/DataDog/dd-trace-go/issues/1452

The example module referenced previously was moved to a different import recently. Thus, if your project tries to depend on `contrib/99designs/gqlgen` you'll end up with an error from being unable to import the example. 

This resolves that by updating the gqlgen version to a more recent version. 

~I didn't upgrade to the most recent version given the contribution guidelines for preferring older, more stable versions. Let me know if I should pick a more recent one!~ Update: I ended up moving to the most recent version since older versions were throwing errors with `go vet` (see the initial commit for errors).

### CODE REVIEW

**Review by katiehockman — APPROVED** [review]

**Comment by david-alza** [comment]
Thanks @katiehockman ! Anything else needed from my end to get this merged in?

**Review by katiehockman — APPROVED** [review]
Nothing else from your end at this point! I'll just make sure the tests are passing in the CI.

**Comment by ajgajg1134** [comment]
It looks like your branch has fallen out-of-date, can you please merge the latest `main` into your branch?

**Comment by david-alza** [comment]
Of course! Just updated @ajgajg1134

**Pull request merged**
