### PR TITLE
chore: upgrade inet.af/netaddr dependency to pass go 1.19 tests

### PR DESCRIPTION
**Pull request by mrkagelui**
addresses #1405

### CODE REVIEW

**Comment by Hellzy** [comment]
Cherry-pick for system-tests validation: https://github.com/DataDog/dd-trace-go/pull/1407

**Review by nsrip-dd — APPROVED** [review]
Thanks @mrkagelui

**Comment by mrkagelui** [comment]
glad to help. not sure how to fix those system tests though

**Comment by nsrip-dd** [comment]
No worries about the system tests, @Hellzy ran them separately and they passed. 👍

**Comment by mrkagelui** [comment]
thanks for the help @Hellzy @nsrip-dd!

**Pull request merged**
