### PR TITLE
contrib/globalsign/mgo: err always nil.

### LINKED ISSUE #2165: contrib/globalsign/mgo: err always nil.
https://github.com/DataDog/dd-trace-go/blob/4c4f51f59642436bb9fafc33e5bc87e485ce7f71/contrib/globalsign/mgo/pipe.go#L49

### PR DESCRIPTION
**Pull request by tttoad**
Fixes #2165

### CODE REVIEW

**Comment by ajgajg1134** [comment]
👋 Thanks for the contribution! One thing I think we should add here is a small unit test to verify this change (and make sure we don't regress later)

**Comment by darccio** [comment]
@tttoad Can you add a unit test to detect future regressions? Thanks!

**Review by darccio — APPROVED** [review]

**Comment by darccio** [comment]
@tttoad After merging this, we have a question about this library/integration. It's fairly old, last release in 2018, and we are not aware of any alternative. Looking around it seems that [juju/mgo](https://github.com/juju/mgo) is a well maintained fork.

What is the current state of MongoDB drivers from your point of view? Is there any reason to keep using `globalsign/mgo`?

**Comment by tttoad** [comment]
@darccio Sorry, I can't give advice... I hardly use `mongodb`, I just saw the problem and fixed it.

**Comment by darccio** [comment]
Don't worry. Thanks for the feedback and the fix, @tttoad!

**Pull request merged**
