### PR TITLE
profiler, ddtrace/tracer: enable code hotspots & endpoints by default with 100% CPU profiling

### PR DESCRIPTION
**Pull request by nsrip-dd**
After testing code hotspots & endpoints together with 100% CPU profiling internally, we've determined that the features have minimal overhead for production workloads and can be safely enabled by default.

### CODE REVIEW

**Review by felixge — DISMISSED** [review]
LGTM, but seems like CI is broken due to go.mod issues again : /. Would you mind taking a look or talking to @DataDog/tracing-go to get it fixed before merging?

**Review by felixge — APPROVED** [review]
LGTM 🥳

**Review by ajgajg1134 — APPROVED** [review]
The code changes look good to me! Is there any documentation anywhere that also needs to change?

**Comment by nsrip-dd** [comment]
Thanks Andrew! I updated the package doc comments for the code hotspots and endpoint options which should cover it for this repo. I'll make sure the default is also documented in the other Datadog docs.

**Pull request merged**
