### PR TITLE
go.mod: update DataDog/datadog-go/v5 to v5.0.2

### PR DESCRIPTION
**Pull request by programmer04**
Version [5.0.2](https://github.com/DataDog/datadog-go/blob/master/CHANGELOG.md#502--2021-11-29) contains important fix for Windows

### CODE REVIEW

**Comment by knusbaum** [comment]
I'll try to get the CI building here...

**Comment by Julio-Guerra** [comment]
@knusbaum, before merging, should we enforce `go mod tidy` to remove old `go.sum` entries?

**Review by Julio-Guerra — DISMISSED** [review]

**Comment by gbbr** [comment]
> should we enforce go mod tidy to remove old go.sum entries?

I think that this is already enforced inside the `milestone` check, unless I'm mistaking.

**Comment by programmer04** [comment]
I removed redundant `go.sum` entries for this library

**Review by Julio-Guerra — APPROVED** [review]

**Comment by Julio-Guerra** [comment]
CI is failing and we are fixing it at the moment :-/
I'll merge this as soon as we're done.

**Pull request merged**
