### PR TITLE
Replace Go version 1.18+1.19 with 1.19+1.22.0

### PR DESCRIPTION
**Pull request by ddyurchenko**
### What does this PR do?

Updates Go version for macrobenchmark runs from 1.18 + 1.19 to 1.19 + 1.22.0.

Tracer and profiler both work correctly after the change.

AppSec doesn't work in 1.22.0
image

For macrobenchmark 1.19 all 3 products work correctly.

### Motivation

Since 9th of January we have a broken macrobenchmark for Go tracer 1.18. The analysis of error has shown that some dependencies now require Go version 1.19 to compile the latest dd-trace-agent.

We need to fix macrobenchmark runs, so they continue to report relevant information.

### Reviewer's Checklist

- [ ] Changed code has unit tests for its functionality at or near 100% coverage.
- [ ] [System-Tests](https://github.com/DataDog/system-tests/) covering this feature have been added and enabled with the va.b.c-dev version tag.
- [ ] There is a benchmark for any new code, or changes to existing code.
- [ ] If this interacts with the agent in a new way, a system test has been added.
- [ ] Add an appropriate team label so this PR gets put in the right place for the release notes.
- [ ] Non-trivial go.mod changes, e.g. adding new modules, are reviewed by @DataDog/dd-trace-go-guild.

For Datadog employees:

- [ ] If this PR touches code that handles credentials of any kind, such as Datadog API keys, I've requested a review from `@DataDog/security-design-and-guidance`.
- [ ] This PR doesn't touch any of that.

Unsure? Have a question? Request a review!

### CODE REVIEW

**Review by eliottness — COMMENTED** [review]
:wave: Thanks for the fix :pray: . Could you use `1.22` instead of `1.22.0` following the pattern from before? If possible of course. By default it should make it use the last patch version of 1.22 instead of strictly using 1.22.0 which is beneficial for us .

Upgrading go-libddwaf should fix this issue (Even though this should not happen)

**Comment by eliottness** [comment]
The issue you are seeing with appsec was fixed in 2.3.1 of go-libddwaf and it was updated upstream (upstream being dd-trace-go) last week so updating your branch should fix your issue

**Comment by ddyurchenko** [comment]
All good after rebasing, no more AppSec errors! :tada:

**Review by eliottness — APPROVED** [review]
Thanks :100:

**Pull request merged**
