### PR TITLE
checkmilestone.go: do not allow merging into triage milestone

### PR DESCRIPTION
**Pull request by knusbaum**
### What does this PR do?

This commit changes the `checkmilestone.go` program so that it does not allow merging when Milestone is `Triage`. 

### Motivation

This is to prevent PR's from being merged but not being associated with a release, and not showing up in release notes.

### Describe how to test/QA your changes

This PR is in milestone Triage. The milestone test should fail. Before merging, I will move it to the correct milestone and ensure that the CI passes.

### Reviewer's Checklist

- [ ] If known, an appropriate milestone has been selected; otherwise the `Triage` milestone is set.
- [ ] Changed code has unit tests for its functionality.
- [ ] If this interacts with the agent in a new way, a system test has been added.

### CODE REVIEW

**Comment by ajgajg1134** [comment]
Should the milestone check here be failing?

**Comment by knusbaum** [comment]
YES IT SHOULD

**Comment by knusbaum** [comment]
There. Now it works.

**Comment by knusbaum** [comment]
Expected failure here:
https://github.com/DataDog/dd-trace-go/actions/runs/4009781438/jobs/6885529082

**Pull request merged**
