### PR TITLE
contrib/dimfeld/httptreemux.v5: default resource namer incorrectly replaces path variables

### PR DESCRIPTION
**Pull request by MNThomson**
### What does this PR do?

This PR fixes a case where the path variable replacement fails under certain conditions. The current implementation "end of path replacement" isn't actually bound to the end of the path and can do a replacement anywhere in the string. E.x. a parameters value is `he` and the url is `/hey/he` it will be replaced as `/:?y/he` (which obviously isn't intended behaviour).

https://github.com/DataDog/dd-trace-go/blob/054d19dbcec79cf5b2a584d12b461e65b8ea24a7/contrib/dimfeld/httptreemux.v5/httptreemux.go#L145-L148

### Motivation

Fixes https://github.com/DataDog/dd-trace-go/issues/2812

### Reviewer's Checklist

- [ ] Changed code has unit tests for its functionality at or near 100% coverage.
- [ ] [System-Tests](https://github.com/DataDog/system-tests/) covering this feature have been added and enabled with the va.b.c-dev version tag.
- [ ] There is a benchmark for any new code, or changes to existing code.
- [ ] If this interacts with the agent in a new way, a system test has been added.
- [ ] Add an appropriate team label so this PR gets put in the right place for the release notes.
- [ ] Non-trivial go.mod changes, e.g. adding new modules, are reviewed by @DataDog/dd-trace-go-guild.

Unsure? Have a question? Request a review!

### CODE REVIEW

**Comment by MNThomson** [comment]
Just checking in, is there anything you folks need from my end? Looking forward to your initial review!

cc @devillecodes

**Comment by darccio** [comment]
@MNThomson Thanks for the contribution, and sorry for the late reply. I approved the CI run to verify that everything is good to go. From my first look, it looks fine to me.

**Review by darccio — APPROVED** [review]

**Comment by MNThomson** [comment]
Thanks @darccio, looks like I'm not authorized to merge this :(. Anything else needed on my end?

**Comment by darccio** [comment]
@MNThomson We are waiting for @DataDog/apm-idm-go approval :) I'll handle everything after their approval.

**Review by rarguelloF — APPROVED** [review]
LGTM, thanks for the fix!

**Comment by darccio** [comment]
@MNThomson Can you merge main into your fork? Thanks!

**Comment by MNThomson** [comment]
@darccio should be good to go!

**Comment by darccio** [comment]
@MNThomson Sorry, a peer DataDog merged another PR. Let me recreate your PR with a new one and I'll handle the merge. Thanks!

**Pull request closed without merging**
