### PR TITLE
WIP: contrib/jackc/pgx.v5: add support for pgx

### PR DESCRIPTION
**Pull request by rarguelloF**
### What does this PR do?

Continuation of https://github.com/DataDog/dd-trace-go/pull/2160

### Reviewer's Checklist

- [ ] Changed code has unit tests for its functionality at or near 100% coverage.
- [ ] There is a benchmark for any new code, or changes to existing code.
- [ ] If this interacts with the agent in a new way, a system test has been added.

For Datadog employees:

- [ ] If this PR touches code that handles credentials of any kind, such as Datadog API keys, I've requested a review from `@DataDog/security-design-and-guidance`.
- [ ] This PR doesn't touch any of that.

Unsure? Have a question? Request a review!

### CODE REVIEW

**Comment by jalaziz** [comment]
What's left to get this over the line? Would love support for pgx.

**Comment by sejin-P** [comment]
Is there any other remained process?

**Comment by Eyal-Shalev** [comment]
@jalaziz
> What's left to get this over the line? Would love support for pgx.

@sejin-P
> Is there any other remained process?

I see that tests are failing

**Comment by sgtsquiggs** [comment]
this is missing several features for parity with database/sql:
* DBMPropagation
  * very difficult the way pgx is currently written
  * adding `TraceQueryInjectComment` (etc...) on the pgx side could resolve this
* many relevant config options
  * WithServiceName
  * WithAnalytics
  * WithAnalyticsRate
  * WithChildSpansOnly
  * WithErrorCheck
  * WithCustomTag
  * WithDBMPropagation (see above)

**Pull request closed without merging**
