### PR TITLE
ddtrace/tracer: removed exactService and exactName from sampling rules

### PR DESCRIPTION
**Pull request by dianashevchenko**
### What does this PR do?
This test removes `exactService` and `exactName`, in favour of just Service and Name fields in the SamplingRule

### Motivation
Spotted inconsistency when running system-tests

### Reviewer's Checklist

- [ ] Changed code has unit tests for its functionality at or near 100% coverage.
- [ ] [System-Tests](https://github.com/DataDog/system-tests/) covering this feature have been added and enabled with the va.b.c-dev version tag.
- [ ] There is a benchmark for any new code, or changes to existing code.
- [ ] If this interacts with the agent in a new way, a system test has been added.
- [ ] Add an appropriate team label so this PR gets put in the right place for the release notes.

For Datadog employees:

- [ ] If this PR touches code that handles credentials of any kind, such as Datadog API keys, I've requested a review from `@DataDog/security-design-and-guidance`.
- [ ] This PR doesn't touch any of that.

Unsure? Have a question? Request a review!

### CODE REVIEW

**Review by knusbaum — COMMENTED** [review]
Could we do a quick benchmark for this stuff? 

It would be nice to have an idea (for this change and the others) what the costs might be.

**Comment by dianashevchenko** [comment]
Yes, will do to compare with main, I guess 🙂

**Comment by darccio** [comment]
@dianashevchenko Where I can read a bit more of context? I'm having some difficulties to understand what inconsistencies lead to these changes. Thanks!

**Comment by dianashevchenko** [comment]
@darccio working according to the latest sampling RFC + there was a new set of tests introduced recently, that's not enabled in CI yet for which these changes are necessary.

**Pull request merged**
