### PR TITLE
contrib: add support for httprouter

### PR DESCRIPTION
**Pull request by shidenkai0**
Hi everyone, 
I implemented full support for github.com/julienschmidt/httprouter, as it is a very popular http mux. This requires a specific implementation to deal with url named parameters.

### CODE REVIEW

**Comment by shidenkai0** [comment]
Seems the tests are failing for something unrelated to this PR (elastic tracer), can someone take a look ?

**Comment by palazzem** [comment]
Hello @shidenkai0 ! thank you for your contribution, we'll take a look as soon as possible! About the CI that is failing, I'm fixing it right now. Will probably ask you to rebase when it's working again.

Will ping you here! Thanks again!

**Comment by palazzem** [comment]
@shidenkai0 the CI should be fixed right now! feel free to rebase on our current master! thank you a lot!

**Comment by shidenkai0** [comment]
Thanks @palazzem, rebase done, waiting for the tests.

**Comment by shidenkai0** [comment]
Hi @palazzem,

 Any news ?

**Comment by palazzem** [comment]
Thanks @shidenkai0! we'll proceed with the review as soon as we finished some internal improvements. We'll do our best to not delay too much this PR. Thank you!

**Comment by pjmuller** [comment]
@palazzem Can this be merged? Would really like to use it with httprouter. Or is there another simple snippet I can use to add the middleware manually?

**Comment by palazzem** [comment]
Hello @shidenkai0 ! sorry about that, we're refactoring a couple of things inside the library so that we can review and merge that one. I'll try to finish the rest of the work as soon as possible.

Thanks a lot for your patience!

**Comment by gbbr** [comment]
Hi @shidenkai0! I'm going to close this because support for this library has been added and approved in the meantime in https://github.com/DataDog/dd-trace-go/pull/115. I apologize for the slow response time and I hope that doesn't discourage you from continuing to contribute to the tracer. I will now be taking over the project and handling issues/PRs full time, so the response time will be a lot better.

**Comment by shidenkai0** [comment]
Hi @gbbr,
Thanks for your response. It is indeed rather annoying to submit a PR to an Open Source project, get ignored, not get any reviews made on your PR, having someone from the team submit a PR with the same features a couple of months later (albeit with some architectural differences) instead of providing a review and comments on the existing PR, then having the duplicate PR merged and the original closed.

I can understand that the project was undergoing some structural and architectural changes.
This matter was mishandled nevertherless.

Thanks for your response anyway, I hope that you taking over the project will push things in the right direction.

**Comment by gbbr** [comment]
> Thanks for your response. It is indeed rather annoying to submit a PR to an Open Source project, get ignored, not get any reviews made on your PR, having someone from the team submit a PR with the same features a couple of months later (albeit with some architectural differences) instead of providing a review and comments on the existing PR, then having the duplicate PR merged and the original closed.

I completely agree with you. This is not something that any of us here at Datadog are proud of or want to continue doing. Unfortunately my colleagues have been very busy and had to choose priorities that best suited the situation at the time. There was nobody to given the needed time to this project. It's not that it was intentionally ignored, but more like there was no time to address PRs and issues (which there were many of). We are all aware of this.

> Thanks for your response anyway, I hope that you taking over the project will push things in the right direction.

That is the reason I am here and that is what I am also aiming for. Once again, apologies for this outcome and I hope this won't stop you from contributing again.

**Pull request closed without merging**
