### PR TITLE
ddtrace: make UseLogger public

### LINKED ISSUE #1331: question: can you make log.UseLogger public API?
Hello everyone.
I think would be awesome if we could change the logger like you guys did in the tests, using the function `UseLogger`: https://github.com/DataDog/dd-trace-go/blob/87a049b142096148eee1c1aae57195aa2a6e3eae/internal/log/log.go#L41

But we can't do it, internal pkg means internal stuff indeed.
And we have a problem 'cause the current log pattern is way different from what we're using here.
We're disabling for a while.

Is there any workaround to inject our logger into it?

Thanks.

### PR DESCRIPTION
**Pull request by nsrip-dd**
Make the internal `UseLogger` function public so that users can specify a
single logger for all tracer and profiler logs. Right now the profiler
doesn't have a configurable logger, and the tracer has the WithLogger
option, which sets the global logger anyway.

Fixes #1331.

### CODE REVIEW

**Comment by KaibutsuX** [comment]
Is there a way to get the old Logger interface so it can be restored? The new public UseLogger function does not return anything compared to the internal's UseLogger.

Without having access to the original logger, I can't perform the original functionality without copy-pasting the code from internal

**Comment by nsrip-dd** [comment]
I suppose we could consider adding a `SwapLogger(new Logger) (old Logger)` interface or something. I'm curious, what's your use case? We have the `undo` functionality internally for testing this library but I'm not sure how useful it would be outside of developing this library.

**Comment by KaibutsuX** [comment]
I'm trying to silence the internal diagnostics like `INFO: Profiler configuration` because they are printed to stderr, they are interpreted as errors in the DD webui. So I have a custom logger that basically says:
```
if !ignoring {
   originalLoggger(msg)
} else {
   // do nothing
}
```

**Comment by KaibutsuX** [comment]
Correct, I want a `ddtrace.GetLogger()`

Just from a design standpoint, it seems unusual that `UseLogger` is a permanent one-way operation that I can never revert, unless I have the original before that.

Yeah I looked through (I got a bit lost in the separation between log and ddtrace/internal/log) and it looks like the internal log is actually directly opening FD2 (stderr) and writing the logs to it. Which means if my custom logger needed to emulate that behavior, I would also need to open 2 or just call the original handler, something like this is what I want to do:
```
type struct mylogger {
    original ddtrace.Logger
    ignoring bool
}
(l *mylogger) Log(m string) {
    if !l.ignoring {
       // Just do whatever DD does normally
       l.original.Log(m)
    } else {
        fmt.Printf("* This message was ignored: %s\n", m)
    }
}
```

**Pull request merged**
